#pragma once

#include <cstddef>

size_t constexpr RAND221_SEED = 0xABCDABCDULL;

constexpr char const * FULL_DECK = (
    "spades ace\n"
    "spades 2\n"
    "spades 3\n"
    "spades 4\n"
    "spades 5\n"
    "spades 6\n"
    "spades 7\n"
    "spades 8\n"
    "spades 9\n"
    "spades 10\n"
    "spades jack\n"
    "spades queen\n"
    "spades king\n"
    "diamonds ace\n"
    "diamonds 2\n"
    "diamonds 3\n"
    "diamonds 4\n"
    "diamonds 5\n"
    "diamonds 6\n"
    "diamonds 7\n"
    "diamonds 8\n"
    "diamonds 9\n"
    "diamonds 10\n"
    "diamonds jack\n"
    "diamonds queen\n"
    "diamonds king\n"
    "clubs ace\n"
    "clubs 2\n"
    "clubs 3\n"
    "clubs 4\n"
    "clubs 5\n"
    "clubs 6\n"
    "clubs 7\n"
    "clubs 8\n"
    "clubs 9\n"
    "clubs 10\n"
    "clubs jack\n"
    "clubs queen\n"
    "clubs king\n"
    "hearts ace\n"
    "hearts 2\n"
    "hearts 3\n"
    "hearts 4\n"
    "hearts 5\n"
    "hearts 6\n"
    "hearts 7\n"
    "hearts 8\n"
    "hearts 9\n"
    "hearts 10\n"
    "hearts jack\n"
    "hearts queen\n"
    "hearts king\n"
);

constexpr char const * FACE_CARDS_DECK = (
    "spades jack\n"
    "spades queen\n"
    "spades king\n"
    "diamonds jack\n"
    "diamonds queen\n"
    "diamonds king\n"
    "clubs jack\n"
    "clubs queen\n"
    "clubs king\n"
    "hearts jack\n"
    "hearts queen\n"
    "hearts king\n"
);

